###
#courseId, assignmentId, studentId, question
POST http://localhost:3000/add_question
Content-Type: application/json
  
 {
  "courseId": "CS101",
  "assignmentId": "Week 1-2 Quiz",
  "studentId": "joey",
  "question": "hello, what is 100 * 100",
  "messagesJSON": "[History of messages]"
 }

###router.get('/get_assignment_data', dashboardData.getAssignmentData);  const { courseId, assignmentId } = req.body;

GET http://localhost:3000/get_assignment_data
Content-Type: application/json
  
 {
  "courseId": "CS101",
  "assignmentId": "A1"
 }

###router.get('/getAllAssignments', dashboardData.getAllAssignments); //  const getAllAssignments = async (req, res) => {

POST http://localhost:3000/getAllAssignments
Content-Type: application/json
  
 {
  "courseId": "CS101"
 }

###router.get('/getAnalytics', dashboardData.getAnalytics) const getAnalytics = async(req, res) => {
        // This will be used to get the analytics for an assignment in the course, 
        //const { courseId, assignmentId } = req.body;

POST http://localhost:3000/getAnalytics
Content-Type: application/json
  
 {
  "courseId": "CS101",
  "assignmentId": "W3 Quiz"
 }

### Get all courses
POST http://localhost:3000/allCourses
Content-Type: application/json