
###
#courseId, assignmentId, studentId, question
POST http://localhost:3000/add_question
Content-Type: application/json
  
 {
  "courseId": "CS101",
  "assignmentId": "A1",
  "studentId": "joey",
  "question": "hello, what is 100 * 100"
 }
 